language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.2
    - DOCKER_REPO="oanhnn/php-stack"
  matrix:
    - APP_ENABLE_HORIZON=1 APP_ENABLE_WORKERS=0 LARAVEL=5.5.*
    - APP_ENABLE_HORIZON=1 APP_ENABLE_WORKERS=0 LARAVEL=5.6.*
    - APP_ENABLE_HORIZON=1 APP_ENABLE_WORKERS=0 LARAVEL=5.7.*
    - APP_ENABLE_HORIZON=0 APP_ENABLE_WORKERS=1 LARAVEL=5.5.*
    - APP_ENABLE_HORIZON=0 APP_ENABLE_WORKERS=1 LARAVEL=5.6.*
    - APP_ENABLE_HORIZON=0 APP_ENABLE_WORKERS=1 LARAVEL=5.7.*

install:
  - travis_retry composer self-update
  # Installing docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version
  - export BUILD_TAG=${TRAVIS_COMMIT::8}
  - export BUILD_CONTAINER="php-stack-$BUILD_TAG"

script:
  # Build image oanhnn/php-stack
  - ./scripts/build.sh

  # Test with Laravel example
  - ./scripts/test.sh

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
