dist: trusty
sudo: false

language: php
php:
  - '7.1'

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.2
    - DOCKER_REPO="oanhnn/php-stack"
  matrix:
    - USE_LARAVEL_HORIZON=1
    - USE_LARAVEL_HORIZON=0

install:
  # Installing docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version
  - export BUILD_TAG=${TRAVIS_COMMIT::8}
  - export BUILD_CONTAINER="php-stack-$BUILD_TAG"

script:
  # Build image oanhnn/php-stack
  - ./scripts/build.sh

  # Test with Laravel example
  - ./scripts/test.sh

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
