sudo: required

language: php
php:
  - '7.1'

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.14.0
  matrix:
    - USE_LARAVEL_HORIZON=1
    - USE_LARAVEL_HORIZON=0

install:
  # Installing docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - composer self-update
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version

script:
  # Build image oanhnn/php-stack
  - docker build -t oanhnn/php-stack:build .

  # Build images for example with Laravel
  - composer create-project --no-dev --prefer-dist laravel/laravel ./laravel 5.5.*
  - cp example-laravel/* example-laravel/.dockerignore laravel/
  - cd laravel
  - if [ "$USE_LARAVEL_HORIZON" -eq "1" ]; then
      composer require laravel/horizon;
    else
      sed -i "s|horizon.ini|workers.ini|gi" Dockerfile;
    fi
  - sed -i "s|DB_CONNECTION=.*|DB_CONNECTION=mysql|i"   .env
  - sed -i "s|DB_HOST=.*|DB_HOST=db|i"                  .env
  - sed -i "s|CACHE_DRIVER=.*|CACHE_DRIVER=redis|i"     .env
  - sed -i "s|SESSION_DRIVER=.*|SESSION_DRIVER=redis|i" .env
  - sed -i "s|MAIL_DRIVER=.*|MAIL_DRIVER=log|i"         .env
  - sed -i "s|REDIS_HOST=.*|REDIS_HOST=redis|i"         .env
  - docker-compose build
  - docker-compose up -d

  # Verifications
  - sleep 30
  - docker-compose logs
  - curl --retry 10 --retry-delay 5 -I http://localhost:80/
  - curl --retry 10 --retry-delay 5 -I http://localhost:8080/

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
    docker tag oanhnn/php-stack:build oanhnn/php-stack:$TRAVIS_TAG;
    docker push oanhnn/php-stack:$TRAVIS_TAG;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker tag oanhnn/php-stack:build oanhnn/php-stack:latest;
    docker push oanhnn/php-stack:latest;
    fi